# Database settings.
database:

  # the name of your JDBC driver
  driverClass: org.mariadb.jdbc.Driver
#  driverClass: org.h2.Driver

  # the username
  user: root

  # the password
  password: password

  # the JDBC URL
#  url: jdbc:h2:./target/hello
  url: jdbc:mariadb://localhost:3306/sasha

server:
#  softNofileLimit: 1000
#  hardNofileLimit: 1000
  applicationConnectors:
    - type: http
      port: 8888
  adminConnectors:
    - type: http
      port: 8881